# 1. Node.js의 경량 버전 기반 이미지 사용
FROM node:18-alpine

# 2. 작업 디렉토리 설정
WORKDIR /app

# 3. package.json과 package-lock.json 복사
COPY package*.json ./

# 4. 종속성 설치
RUN npm install

# 5. 애플리케이션 소스 코드 복사
COPY . .

# 6. 애플리케이션 소스 코드 복사
# COPY .env .env

# 6. Nest.js 애플리케이션 빌드
RUN npm run build

# 7. 포트 설정 (Nest.js 기본 포트는 3001, 변경 가능)
EXPOSE 8080

# 8. 애플리케이션 시작
CMD ["npm", "run", "start:prod"]